spring:
  application:
    name: EcommerceDemo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/ecommerce
    username: martin
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true